In [2]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

def amazon_search_products(query, num_pages=10):
    results = []

    for page in range(1, num_pages + 1):
        url = f"https://www.amazon.in/s?k={query}&page={page}"
        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0;Win64) AppleWebkit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'
        }
        response = requests.get(url, headers=headers)
        html_content = response.text
        soup = BeautifulSoup(html_content, 'html.parser')

        product_containers = soup.find_all("div", class_="sg-col-inner")
        for container in product_containers:
            title_element = container.find("span", class_="a-size-medium a-color-base a-text-normal")
            price_element = container.find("span", class_="a-price-whole")
            star_element = container.find("span", class_="a-icon-alt")
            sales_element = container.find("span", class_="a-size-base s-underline-text")
            disc_element = container.select_one("span:nth-child(3)")

            if title_element is None or price_element is None or star_element is None or sales_element is None or disc_element is None :
                continue

            title = title_element.text.strip()
            price = price_element.text.strip()
            stars = star_element.text.strip()
            sales = sales_element.text.strip()
            disc = disc_element.text.strip()

            result = {
                'title': title,
                'price': price,
                'stars': stars,
                'sales': sales,
                'disc': disc
            }
            results.append(result)

    return results

q = input("Enter the product name: ")
product_search_results = amazon_search_products(q)

if product_search_results:
    df1 = pd.DataFrame(product_search_results)
    print(df1)
else:
    print("No results found.")

                                                 title   price  \
0    Redmi 12C (Lavender Purple, 4GB RAM, 64GB Stor...   6,999
1    Redmi 12C (Lavender Purple, 4GB RAM, 64GB Stor...   6,999
2    OnePlus 11 5G (Titan Black, 16GB RAM, 256GB St...  61,999
3    Redmi A2 (Aqua Blue, 2GB RAM, 32GB Storage) | ...   6,299
4    realme C55 (Rainforest, 6GB RAM, 64 Storage) |...  10,713
..                                                 ...     ...
309           Redmi 2GB RAM, 16GB Storage Mi 6A, Black   6,999
310  TECNO Phantom X2 Pro 5G Stardust Grey (12GB RA...  44,999
311  Oppo Reno4 Pro Silky White, 8GB RAM, 128GB Sto...  28,200
312  Nokia G42 5G | Snapdragon® 480+ 5G | 50MP Trip...  12,499
313  OnePlus Nord 3 5G (Misty Green, 8GB RAM, 128GB...  33,999

                  stars   sales       disc
0    3.9 out of 5 stars   8,446
1    3.9 out of 5 stars   8,446
2    4.3 out of 5 stars   4,245
3    3.8 out of 5 stars   4,238  (30% off)
4    4.0 out of 5 stars     246  (23% off)
..                  ...     ...        ...
309  4.1 out of 5 stars  97,918  (13% off)
310  3.6 out of 5 stars     185  (27% off)
311  4.3 out of 5 stars     881  (26% off)
312  3.7 out of 5 stars     279
313  4.0 out of 5 stars   2,047

[314 rows x 5 columns]

In [3]:
def flipkart_search_products(query, num_pages=10):
    results = []

    for page in range(1, num_pages + 1):
        url = f"https://www.flipkart.com/search?q={query}&page={page}"
        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0;Win64) AppleWebkit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'
        }
        response = requests.get(url, headers=headers)
        html_content = response.text
        soup = BeautifulSoup(html_content, 'html.parser')

        product_containers = soup.find_all("div", class_="_4ddWXP")
        for container in product_containers:
            title_element = container.find("a", class_="s1Q9rs")
            price_element = container.find("div", class_="_30jeq3")
            star_element = container.find("div", class_="_3LWZlK")
            sales_element = container.find("span", class_="_2_R_DZ")
            disc_element = container.select_one("div:nth-child(1)")

            if title_element is None or price_element is None or star_element is None or sales_element is None or disc_element is None:
                continue

            title = title_element.text.strip()
            price = price_element.text.strip()
            stars = star_element.text.strip()
            sales = sales_element.text.strip()
            disc = disc_element.text.strip()
            
            result = {
                'title': title,
                'price': price,
                'stars':stars,
                'sales':sales,
                'disc':disc
            }
            results.append(result)

    return results

q = input("Enter the product name: ")
product_search_results = amazon_search_products(q)

if product_search_results:
    df2 = pd.DataFrame(product_search_results)
    print(df2)
else:
    print("No results found.")

                                                 title   price  \
0    Redmi 12C (Lavender Purple, 4GB RAM, 64GB Stor...   6,999
1    Redmi 12C (Lavender Purple, 4GB RAM, 64GB Stor...   6,999
2    Redmi 12C (Lavender Purple, 4GB RAM, 64GB Stor...   6,999
3    OnePlus 11 5G (Titan Black, 16GB RAM, 256GB St...  61,999
4    OnePlus 11 5G (Titan Black, 16GB RAM, 256GB St...  61,999
..                                                 ...     ...
375  Vivo V23 5G(Sunshine Gold, 12GB RAM, 256GB Sto...  33,900
376  Samsung Galaxy S23 5G (Lavender, 8GB, 128GB St...  74,999
377  Redmi 12C (Lavender Purple, 4GB RAM, 64GB Stor...   6,999
378  Nokia G42 5G | Snapdragon® 480+ 5G | 50MP Trip...  12,499
379  OnePlus Nord 3 5G (Misty Green, 8GB RAM, 128GB...  33,999

                  stars  sales       disc
0    3.9 out of 5 stars  8,446
1    3.9 out of 5 stars  8,446
2    3.9 out of 5 stars  8,446
3    4.3 out of 5 stars  4,245
4    4.3 out of 5 stars  4,245
..                  ...    ...        ...
375  4.1 out of 5 stars    700  (11% off)
376  4.5 out of 5 stars    913  (17% off)
377  3.9 out of 5 stars  8,446  (50% off)
378  3.7 out of 5 stars    279
379  4.0 out of 5 stars  2,047

[380 rows x 5 columns]

In [4]:
df1

,title,price,stars,sales,disc
0,"Redmi 12C (Lavender Purple, 4GB RAM, 64GB Stor...","6,999",3.9 out of 5 stars,"8,446",
1,"Redmi 12C (Lavender Purple, 4GB RAM, 64GB Stor...","6,999",3.9 out of 5 stars,"8,446",
2,"OnePlus 11 5G (Titan Black, 16GB RAM, 256GB St...","61,999",4.3 out of 5 stars,"4,245",
3,"Redmi A2 (Aqua Blue, 2GB RAM, 32GB Storage) | ...","6,299",3.8 out of 5 stars,"4,238",(30% off)
4,"realme C55 (Rainforest, 6GB RAM, 64 Storage) |...","10,713",4.0 out of 5 stars,246,(23% off)
...,...,...,...,...,...
309,"Redmi 2GB RAM, 16GB Storage Mi 6A, Black","6,999",4.1 out of 5 stars,"97,918",(13% off)
310,TECNO Phantom X2 Pro 5G Stardust Grey (12GB RA...,"44,999",3.6 out of 5 stars,185,(27% off)
311,"Oppo Reno4 Pro Silky White, 8GB RAM, 128GB Sto...","28,200",4.3 out of 5 stars,881,(26% off)
312,Nokia G42 5G | Snapdragon® 480+ 5G | 50MP Trip...,"12,499",3.7 out of 5 stars,279,
313,"OnePlus Nord 3 5G (Misty Green, 8GB RAM, 128GB...","33,999",4.0 out of 5 stars,"2,047",

In [6]:
df2

,title,price,stars,sales,disc
0,"Redmi 12C (Lavender Purple, 4GB RAM, 64GB Stor...","6,999",3.9 out of 5 stars,"8,446",
1,"Redmi 12C (Lavender Purple, 4GB RAM, 64GB Stor...","6,999",3.9 out of 5 stars,"8,446",
2,"Redmi 12C (Lavender Purple, 4GB RAM, 64GB Stor...","6,999",3.9 out of 5 stars,"8,446",
3,"OnePlus 11 5G (Titan Black, 16GB RAM, 256GB St...","61,999",4.3 out of 5 stars,"4,245",
4,"OnePlus 11 5G (Titan Black, 16GB RAM, 256GB St...","61,999",4.3 out of 5 stars,"4,245",
...,...,...,...,...,...
375,"Vivo V23 5G(Sunshine Gold, 12GB RAM, 256GB Sto...","33,900",4.1 out of 5 stars,700,(11% off)
376,"Samsung Galaxy S23 5G (Lavender, 8GB, 128GB St...","74,999",4.5 out of 5 stars,913,(17% off)
377,"Redmi 12C (Lavender Purple, 4GB RAM, 64GB Stor...","6,999",3.9 out of 5 stars,"8,446",(50% off)
378,Nokia G42 5G | Snapdragon® 480+ 5G | 50MP Trip...,"12,499",3.7 out of 5 stars,279,
379,"OnePlus Nord 3 5G (Misty Green, 8GB RAM, 128GB...","33,999",4.0 out of 5 stars,"2,047",

In [5]:
df1.to_csv('amazon.csv')

In [7]:
df2.to_csv('flipkart.csv')

In [48]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

results = []

m1 = [0, 1, 2, 3, 4, 5, 6]
for page in m1:  # Scraping the first 5 pages
    url = f"https://www.imdb.com/search/title/?groups=top_250&sort=user_rating,desc&start={page}1&ref_=adv_prv"
    response = requests.get(url)
    html_content = response.text
    soup = BeautifulSoup(html_content, 'html.parser')

    movie_containers = soup.find_all("div", class_="lister-item-content")

    for i in movie_containers:
        movie_name_element = i.select_one("h3 > a")
        year_element = i.find("span", class_="lister-item-year text-muted unbold")
        time_element = i.find("span", class_="runtime")
        genre_element = i.find("span", class_="genre")
        rating_element = i.select_one("strong")
        metascore_element = i.find("span", class_="metascore favorable")

        if (
            movie_name_element is None
            or year_element is None
            or time_element is None
            or genre_element is None
            or rating_element is None
        ):
            continue

        movie = movie_name_element.text.strip()
        year = year_element.text.strip()
        time = time_element.text.strip()
        genre = genre_element.text.strip()
        rating = rating_element.text.strip()
        metascore = metascore_element

        result = {
            'movie': movie,
            'year': year,
            'time': time,
            'genre': genre,
            'rating': rating,
            'metascore': metascore
        }

        results.append(result)

df2 = pd.DataFrame(results)
df2

,movie,year,time,genre,rating,metascore
0,The Shawshank Redemption,(1994),142 min,Drama,9.3,[82 ]
1,The Godfather,(1972),175 min,"Crime, Drama",9.2,[100 ]
2,The Dark Knight,(2008),152 min,"Action, Crime, Drama",9.0,[84 ]
3,Schindler's List,(1993),195 min,"Biography, Drama, History",9.0,[95 ]
4,The Lord of the Rings: The Return of the King,(2003),201 min,"Action, Adventure, Drama",9.0,[94 ]
...,...,...,...,...,...,...
345,Mononoke-hime,(1997),134 min,"Animation, Action, Adventure",8.3,[76 ]
346,Vertigo,(1958),128 min,"Mystery, Romance, Thriller",8.3,[100 ]
347,Citizen Kane,(1941),119 min,"Drama, Mystery",8.3,[100 ]
348,To Kill a Mockingbird,(1962),129 min,"Crime, Drama",8.3,[88 ]
349,Metropolis,(1927),153 min,"Drama, Sci-Fi",8.3,[98 ]

In [50]:
df2.isna().sum()

movie         0
year          0
time          0
genre         0
rating        0
metascore    24
dtype: int64

In [11]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

results = []

for i in range(1):
    url = "https://www.flipkart.com/search?q=iphones&page="+str(i)
    response = requests.get(url)
    html_content = response.text
    soup = BeautifulSoup(html_content,"html.parser")

    #product names

    box1 = soup.find_all("div",class_="_2kHMtA")
    for box in box1:
        name = box.find("div",class_="_4rR01T")
        price = box.find("div",class_="_30jeq3 _1_WHN1")
        des = box.find("ul",class_="_1xgFaf")
        rat = box.find("div",class_="_3LWZlK")
        off = box.find("div",class_="_3Ay6Sb")
        
        names = name.text.strip()
        prices = price.text.strip()
        Desc = des.text.strip()
        ratings = rat.text.strip()
        offers = off.text.strip()
        
        result = {"Product Name":names,"Product Price":prices,"Description":Desc,"Rating":ratings,"Offers":offers}
        results.append(result)

data = pd.DataFrame(results)
print(data)

                                Product Name Product Price  \
0             APPLE iPhone 14 (Blue, 128 GB)       ₹58,999
1         APPLE iPhone 14 (Midnight, 128 GB)       ₹59,999
2        APPLE iPhone 14 (Starlight, 128 GB)       ₹59,999
3           APPLE iPhone 14 (Purple, 128 GB)       ₹59,999
4   APPLE iPhone 14 Plus (Starlight, 128 GB)       ₹67,999
5    APPLE iPhone 14 Plus (Midnight, 128 GB)       ₹67,999
6      APPLE iPhone 14 Plus (Purple, 128 GB)       ₹67,999
7        APPLE iPhone 14 (Starlight, 256 GB)       ₹69,999
8         APPLE iPhone 14 (Midnight, 256 GB)       ₹69,999
9             APPLE iPhone 14 (Blue, 256 GB)       ₹68,999
10       APPLE iPhone 14 Plus (Blue, 128 GB)       ₹68,999
11             APPLE iPhone 12 (Blue, 64 GB)       ₹42,999
12          APPLE iPhone 14 (Purple, 256 GB)       ₹69,999
13            APPLE iPhone 12 (Blue, 128 GB)       ₹48,999
14           APPLE iPhone 15 (Black, 128 GB)       ₹76,990
15            APPLE iPhone 15 (Blue, 128 GB)       ₹76,990
16            APPLE iPhone 12 (White, 64 GB)       ₹42,999
17            APPLE iPhone 12 (Green, 64 GB)       ₹42,999
18           APPLE iPhone 12 (Black, 128 GB)       ₹48,999
19            APPLE iPhone 15 (Blue, 256 GB)       ₹86,990
20            APPLE iPhone 12 (Black, 64 GB)       ₹42,999
21           APPLE iPhone 15 (Green, 128 GB)       ₹76,990
22           APPLE iPhone 15 (Black, 256 GB)       ₹86,990
23           APPLE iPhone 12 (White, 128 GB)       ₹48,999

                                          Description Rating   Offers
0   128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...    4.6  15% off
1   128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...    4.6  14% off
2   128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...    4.6  14% off
3   128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...    4.6  14% off
4   128 GB ROM17.02 cm (6.7 inch) Super Retina XDR...    4.6  14% off
5   128 GB ROM17.02 cm (6.7 inch) Super Retina XDR...    4.6  14% off
6   128 GB ROM17.02 cm (6.7 inch) Super Retina XDR...    4.6  14% off
7   256 GB ROM15.49 cm (6.1 inch) Super Retina XDR...    4.6  12% off
8   256 GB ROM15.49 cm (6.1 inch) Super Retina XDR...    4.6  12% off
9   256 GB ROM15.49 cm (6.1 inch) Super Retina XDR...    4.6  13% off
10  128 GB ROM17.02 cm (6.7 inch) Super Retina XDR...    4.6  13% off
11  64 GB ROM15.49 cm (6.1 inch) Super Retina XDR ...    4.6  13% off
12  256 GB ROM15.49 cm (6.1 inch) Super Retina XDR...    4.6  12% off
13  128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...    4.6  10% off
14  128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...    4.6   3% off
15  128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...    4.6   3% off
16  64 GB ROM15.49 cm (6.1 inch) Super Retina XDR ...    4.6  13% off
17  64 GB ROM15.49 cm (6.1 inch) Super Retina XDR ...    4.6  13% off
18  128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...    4.6  10% off
19  256 GB ROM15.49 cm (6.1 inch) Super Retina XDR...    4.6   3% off
20  64 GB ROM15.49 cm (6.1 inch) Super Retina XDR ...    4.6  13% off
21  128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...    4.6   3% off
22  256 GB ROM15.49 cm (6.1 inch) Super Retina XDR...    4.6   3% off
23  128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...    4.6  10% off

In [12]:
data.to_csv("iphone_flipkart.csv")

In [13]:
data

,Product Name,Product Price,Description,Rating,Offers
0,"APPLE iPhone 14 (Blue, 128 GB)","₹58,999",128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,4.6,15% off
1,"APPLE iPhone 14 (Midnight, 128 GB)","₹59,999",128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,4.6,14% off
2,"APPLE iPhone 14 (Starlight, 128 GB)","₹59,999",128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,4.6,14% off
3,"APPLE iPhone 14 (Purple, 128 GB)","₹59,999",128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,4.6,14% off
4,"APPLE iPhone 14 Plus (Starlight, 128 GB)","₹67,999",128 GB ROM17.02 cm (6.7 inch) Super Retina XDR...,4.6,14% off
5,"APPLE iPhone 14 Plus (Midnight, 128 GB)","₹67,999",128 GB ROM17.02 cm (6.7 inch) Super Retina XDR...,4.6,14% off
6,"APPLE iPhone 14 Plus (Purple, 128 GB)","₹67,999",128 GB ROM17.02 cm (6.7 inch) Super Retina XDR...,4.6,14% off
7,"APPLE iPhone 14 (Starlight, 256 GB)","₹69,999",256 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,4.6,12% off
8,"APPLE iPhone 14 (Midnight, 256 GB)","₹69,999",256 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,4.6,12% off
9,"APPLE iPhone 14 (Blue, 256 GB)","₹68,999",256 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,4.6,13% off
10,"APPLE iPhone 14 Plus (Blue, 128 GB)","₹68,999",128 GB ROM17.02 cm (6.7 inch) Super Retina XDR...,4.6,13% off
11,"APPLE iPhone 12 (Blue, 64 GB)","₹42,999",64 GB ROM15.49 cm (6.1 inch) Super Retina XDR ...,4.6,13% off
12,"APPLE iPhone 14 (Purple, 256 GB)","₹69,999",256 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,4.6,12% off
13,"APPLE iPhone 12 (Blue, 128 GB)","₹48,999",128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,4.6,10% off
14,"APPLE iPhone 15 (Black, 128 GB)","₹76,990",128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,4.6,3% off
15,"APPLE iPhone 15 (Blue, 128 GB)","₹76,990",128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,4.6,3% off
16,"APPLE iPhone 12 (White, 64 GB)","₹42,999",64 GB ROM15.49 cm (6.1 inch) Super Retina XDR ...,4.6,13% off
17,"APPLE iPhone 12 (Green, 64 GB)","₹42,999",64 GB ROM15.49 cm (6.1 inch) Super Retina XDR ...,4.6,13% off
18,"APPLE iPhone 12 (Black, 128 GB)","₹48,999",128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,4.6,10% off
19,"APPLE iPhone 15 (Blue, 256 GB)","₹86,990",256 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,4.6,3% off
20,"APPLE iPhone 12 (Black, 64 GB)","₹42,999",64 GB ROM15.49 cm (6.1 inch) Super Retina XDR ...,4.6,13% off
21,"APPLE iPhone 15 (Green, 128 GB)","₹76,990",128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,4.6,3% off
22,"APPLE iPhone 15 (Black, 256 GB)","₹86,990",256 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,4.6,3% off
23,"APPLE iPhone 12 (White, 128 GB)","₹48,999",128 GB ROM15.49 cm (6.1 inch) Super Retina XDR...,4.6,10% off